[package]
name = "dwarf-to-json"
version = "0.1.10"
authors = ["Yury Delendik <ydelendik@mozilla.com>"]

[dependencies]
vlq = "0.5.1"
gimli = "0.16.0"
serde_json = "1.0.26"

[lib]
crate-type = ["cdylib"]
